name: PR

on:
  pull_request:
    paths-ignore:
      - 'README.md'
  schedule:
    - cron: '0 20 * * 6'

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
    steps:
      - uses: actions/checkout@v6
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
      - name: Run tests
        run: cargo test --workspace

  lint:
    name: fmt & lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
      - name: Rustfmt Check
        run: cargo fmt --check --all
      - name: Clippy check
        run: cargo clippy --workspace

  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-msrv
      - name: Check MSRV
        run: cargo msrv verify --output-format json
